# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Stylistic rules (enforcing consistent code style)
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_single_quotes: true # Optional: common in Dart/Flutter teams
    
    # Error avoidance rules
    avoid_print: true # Prevents leaving print() calls in production code
    use_key_in_widget_constructors: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    
    # Ordering
    directives_ordering: true

analyzer:
  exclude:
    - "**/*.g.dart" # Excludes generated files (useful later for JSON serialization)
    - "**/*.freezed.dart"