// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_xnp3spJSLq6zks_Kfa6R0NosVYJbtAs',
    appId: '1:313850698290:web:5e5544983564be1c993a2b',
    messagingSenderId: '313850698290',
    projectId: 'fixit-3580c',
    authDomain: 'fixit-3580c.firebaseapp.com',
    storageBucket: 'fixit-3580c.firebasestorage.app',
    measurementId: 'G-95NHGM0CSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaV4Zpu6WmeS4YjtV0NYyYBeLI0hOrjkE',
    appId: '1:313850698290:android:5517a9a669f2371a993a2b',
    messagingSenderId: '313850698290',
    projectId: 'fixit-3580c',
    storageBucket: 'fixit-3580c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADWRBzqxyU1Cjn0dDr2bMzNPoNfXlpso4',
    appId: '1:313850698290:ios:5521c2c2cc3e7704993a2b',
    messagingSenderId: '313850698290',
    projectId: 'fixit-3580c',
    storageBucket: 'fixit-3580c.firebasestorage.app',
    iosBundleId: 'com.example.fixItApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADWRBzqxyU1Cjn0dDr2bMzNPoNfXlpso4',
    appId: '1:313850698290:ios:5521c2c2cc3e7704993a2b',
    messagingSenderId: '313850698290',
    projectId: 'fixit-3580c',
    storageBucket: 'fixit-3580c.firebasestorage.app',
    iosBundleId: 'com.example.fixItApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_xnp3spJSLq6zks_Kfa6R0NosVYJbtAs',
    appId: '1:313850698290:web:cfe5e30585c3b69d993a2b',
    messagingSenderId: '313850698290',
    projectId: 'fixit-3580c',
    authDomain: 'fixit-3580c.firebaseapp.com',
    storageBucket: 'fixit-3580c.firebasestorage.app',
    measurementId: 'G-L8WCB94Y1Y',
  );
}
